export const LOAD_LANG = 'LOAD_LANG'
export const SET_USER = 'SET_USER'
export const SET_MENU = 'SET_MENU'
export const USER_LOGOUT = 'USER_LOGOUT'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const SWITCH_MODE = 'SWITCH_MODE'
export const SET_PAGE = 'SET_PAGE'
