/* eslint-disable no-template-curly-in-string */
/* eslint-disable no-undef */
export default {
  "veeValidate_default": "The {field} value is not valid.",
  "veeValidate_after": "The {field} must be after {target}.",
  "veeValidate_after_equal": "The {field} must be after or equal to {target}.",
  "veeValidate_alpha_dash": "The {field} field may contain alpha-numeric characters as well as dashes and underscores.",
  "veeValidate_alpha_num": "The {field} field may only contain alpha-numeric characters.",
  "veeValidate_alpha_spaces": "The {field} field may only contain alphabetic characters as well as spaces.",
  "veeValidate_alpha": "The {field} field may only contain alphabetic characters.",
  "veeValidate_before": "The {field} must be before {target}.",
  "veeValidate_before_equal": "The {field} must be before or equal to {target}.",
  "veeValidate_between": "The {field} field must be between {min} and {max}.",
  "veeValidate_confirmed": "The {field} confirmation does not match.",
  "veeValidate_credit_card": "The {field} field is invalid.",
  "veeValidate_date_between": "The {field} must be between {min} and {max}.",
  "veeValidate_date_format": "The {field} must be in the format {format}.",
  "veeValidate_decimal": "The {field} field must be numeric and may contain {decimals} decimal points.",
  "veeValidate_digits": "The {field} field must be numeric and exactly contain {length} digits.",
  "veeValidate_dimensions": "The {field} field must be {width} pixels by {height} pixels.",
  "veeValidate_email": "The {field} field must be a valid email.",
  "veeValidate_ext": "The {field} field must be a valid file.",
  "veeValidate_image": "The {field} field must be an image.",
  "veeValidate_in": "The {field} field must be a valid value.",
  "veeValidate_integer": "The {field} field must be an integer.",
  "veeValidate_ip": "The {field} field must be a valid ip address.",
  "veeValidate_length": "The {field} length must be {length}.",
  "veeValidate_length_max": "The {field} length be between {length} and {max}.",
  "veeValidate_max": "The {field} field may not be greater than {length} characters.",
  "veeValidate_max_value": "The {field} field must be {max} or less.",
  "veeValidate_mimes": "The {field} field must have a valid file type.",
  "veeValidate_min": "The {field} field must be at least {length} characters.",
  "veeValidate_min_value": "The {field} field must be {min} or more.",
  "veeValidate_not_in": "The {field} field must be a valid value.",
  "veeValidate_numeric": "The {field} field may only contain numeric characters.",
  "veeValidate_regex": "The {field} field format is invalid.",
  "veeValidate_required": "The {field} field is required.",
  "veeValidate_size": "The {field} size must be less than {size}.",
  "veeValidate_url": "The {field} field is not a valid URL."
}
