/* eslint-disable no-template-curly-in-string */
/* eslint-disable no-undef */
export default {
  "veeValidate_default": "Nilai {field} tidak sah.",
  "veeValidate_after": "{field} harus sebelum {target}.",
  "veeValidate_after_equal": "{field} harus sebelum atau sama dengan {target}.",
  "veeValidate_alpha_dash": "{field} boleh mengandung karakter alfanumerik, tanda hubung, dan garis bawah.",
  "veeValidate_alpha_num": "{field} hanya boleh mengandung karakter alfanumerik.",
  "veeValidate_alpha_spaces": "{field} hanya boleh berisi karakter alfabet serta spasi.",
  "veeValidate_alpha": "{field} hanya boleh mengandung karakter alfabet.",
  "veeValidate_before": "{field} harus setelah {target}.",
  "veeValidate_before_equal": "{field} harus setelah atau sama dengan  {target}.",
  "veeValidate_between": "{field} harus di antara {min} dan {max}.",
  "veeValidate_confirmed": "{field} tidak cocok dengan {confirmedField}.",
  "veeValidate_credit_card": "{field} tidak sah.",
  "veeValidate_date_between": "{field} harus di antara {min} dan {max}.",
  "veeValidate_date_format": "{field} harus dalam format {format}.",
  "veeValidate_decimal": "{field} harus berupa angka dan boleh mengandung {decimals} titik desimal.",
  "veeValidate_digits": "{field} harus berupa {length} digit angka.",
  "veeValidate_dimensions": "{field} harus berdimensi lebar {width} pixel dan tinggi {height} pixel.",
  "veeValidate_email": "{field} harus berupa alamat surel yang benar.",
  "veeValidate_ext": "{field} harus berupa berkas yang benar.",
  "veeValidate_image": "{field} harus berupa gambar.",
  "veeValidate_in": "{field} harus berupa nilai yang sah.",
  "veeValidate_integer": "{field} harus berupa bilangan bulat.",
  "veeValidate_ip": "{field} harus berupa alamat ip yang sah.",
  "veeValidate_length": "Panjang {field} harus tepat {length}.",
  "veeValidate_length_max": "Panjang {field} harus di antara {length} dan {max}.",
  "veeValidate_max": "{field} tidak boleh lebih dari {length} karakter.",
  "veeValidate_max_value": "Nilai {field} tidak boleh lebih dari {size}.",
  "veeValidate_mimes": "Tipe berkas {field} harus benar.",
  "veeValidate_min": "{field} minimal mengandung {length} karakter.",
  "veeValidate_min_value": "Nilai {field} tidak boleh kurang dari {size}.",
  "veeValidate_not_in": "{field} harus berupa nilai yang sah.",
  "veeValidate_numeric": "{field} harus berupa angka.",
  "veeValidate_regex": "Format {field} salah.",
  "veeValidate_required": "{field} harus diisi ya",
  "veeValidate_size": "{field} harus lebih kecil dari {size}.",
  "veeValidate_url": "{field} harus berupa tautan yang benar."
}
